version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api
    command: ["./api"]
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ecommerce
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-secret-key
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_S3_REGION=us-east-1
      - AWS_S3_ACCESS_KEY=localstack
      - AWS_S3_SECRET_KEY=localstack
      - AWS_S3_BUCKET=ecommerce-uploads
      - AWS_EVENT_QUEUE_NAME=ecommerce-events
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@example.com
    depends_on:
      - postgres
      - localstack
    restart: unless-stopped

  notifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notifier
    command: ["./notifier"]
    environment:
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/ecommerce-events
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_S3_REGION=us-east-1
      - AWS_S3_ACCESS_KEY=localstack
      - AWS_S3_SECRET_KEY=localstack
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@example.com
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ecommerce
      - DB_SSL_MODE=disable
    depends_on:
      - localstack
      - mailpit
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh


  cdn:
    image: nginx:alpine
    container_name: cdn
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../uploads:/var/www/uploads

volumes:
  postgres_data:
  localstack_data:
  mailpit_data: